site_name: CompSci HQ
site_description: 'Notes for Semester 5 of Computer Science at Dawson'
site_author: 'Tiffany'
site_url: ''
site_favicon: 'images/favicon.ico'

# Documentation and theme
theme: 'material'

# Options
extra:
  font:
    text: 'Firacode'
    code: 'Firacode'

# Extensions
markdown_extensions:
  - admonition
  - codehilite(guess_lang=false)
  - toc(permalink=true)
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde