site_name: CompSci HQ
site_description: 'Notes for Semester 5 of Computer Science at Dawson'
site_author: 'sirMerr'
site_url: 'https://sirmerr.github.io/compsci-notes/'
site_favicon: 'assets/images/favicon.ico'
repo_url: https://github.com/sirMerr/compsci-notes
repo_name: sirmerr/compsci-notes

# Documentation and theme
theme: 'material'

# Options
extra:
  palette:
    primary: 'purple'
    accent: 'indigo'

# Extensions
markdown_extensions:
  - admonition
  - codehilite(guess_lang=false, linenums=true)
  - toc(permalink=true)
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde