DROP DATABASE IF EXISTS HOSPITALDB;

CREATE DATABASE HOSPITALDB;

USE HOSPITALDB;

GRANT ALL PRIVILEGES ON HOSPITALDB.* TO TheUser@"%" IDENTIFIED BY "pancake";
GRANT ALL PRIVILEGES ON HOSPITALDB.* TO TheUser@"localhost" IDENTIFIED BY "pancake";

FLUSH PRIVILEGES;
