DROP DATABASE IF EXISTS HOSPITALDB;
CREATE DATABASE HOSPITALDB;

USE HOSPITALDB;

DROP USER IF EXISTS TheUser@localhost;

CREATE USER TheUser@'localhost' IDENTIFIED BY 'pancake';

GRANT ALL ON HOSPITALDB.* TO TheUser@'localhost';

FLUSH PRIVILEGES;
